server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: game-elements-service
          uri: http://172.17.112.1:8081
          predicates:
            - Path=/game-elements/**
          filters:
            - StripPrefix=1


    loadbalancer:
      ribbon:
        enabled: false

  httpclient:
    connect-timeout: 5000
    response-timeout: 10s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
